import type { PaperCandidate, PaperDetail, SearchResponse } from "./types";

export const demoCandidates: PaperCandidate[] = [
  {
    id: "eagle-3",
    title: "EAGLE-3: Efficient Speculative Decoding for Mixture-of-Experts Inference",
    authors: ["Mira Chen", "Arjun Rao", "Sofia Lind"],
    year: 2025,
    venue: "NeurIPS 2025",
    abstract: "A verifier-guided decoding architecture that uses lightweight draft generation and parallel acceptance to reduce serving latency for sparse expert models.",
    relevanceScore: 0.94,
    relevanceReason: "Directly studies speculative decoding and sparse expert inference.",
    source: "Semantic Scholar",
    arxivId: "2504.01842",
  },
  {
    id: "draftmesh",
    title: "DraftMesh: Parallel Candidate Verification for Sparse Language Models",
    authors: ["Noah Williams", "Keiko Tanaka", "Ibrahim Haddad"],
    year: 2024,
    venue: "ICML 2024",
    abstract: "DraftMesh separates candidate generation from verification and schedules expert calls in parallel across a shared inference mesh.",
    relevanceScore: 0.88,
    relevanceReason: "Useful comparison point for verifier scheduling and expert parallelism.",
    source: "arXiv",
    arxivId: "2407.09210",
  },
  {
    id: "routeformer",
    title: "RouteFormer: Token Routing and Latency-Aware Expert Selection",
    authors: ["Priya Nair", "Jon Bell", "Matteo Ricci"],
    year: 2025,
    venue: "ACL 2025",
    abstract: "An analysis of how routing decisions, batching, and expert load affect end-to-end latency in mixture-of-experts transformers.",
    relevanceScore: 0.81,
    relevanceReason: "Provides context for the systems constraints behind MoE decoding.",
    source: "Semantic Scholar",
    doi: "10.0000/paperscope.demo",
  },
  {
    id: "swiftverify",
    title: "SwiftVerify: Adaptive Verification Budgets for Autoregressive Generation",
    authors: ["Lena Okafor", "Hugo Martin"],
    year: 2023,
    venue: "EMNLP 2023",
    abstract: "Adaptive verifier budgets trade acceptance rate against compute cost for faster generation under changing prompt distributions.",
    relevanceScore: 0.76,
    relevanceReason: "A nearby method with a different approach to verification budget selection.",
    source: "Semantic Scholar",
    arxivId: "2310.01451",
  },
];

export const demoSearchResponse: SearchResponse = {
  intent: {
    originalQuery: "efficient speculative decoding for MoE inference",
    normalizedTopic: "Efficient speculative decoding for mixture-of-experts inference",
    coreConcepts: ["speculative decoding", "mixture-of-experts", "parallel verification"],
    relatedTerms: ["draft model", "token acceptance", "expert routing"],
    methods: ["parallel verification", "adaptive batching", "latency-aware routing"],
    targetProblems: ["decode latency", "expert imbalance", "verification overhead"],
    searchQueries: [
      "efficient speculative decoding mixture of experts",
      "parallel token verification sparse language models",
      "MoE inference latency draft verifier",
    ],
  },
  candidates: demoCandidates,
  reranked: true,
  demo: true,
};

export const demoPaper: PaperDetail = {
  id: "eagle-3",
  title: demoCandidates[0].title,
  authors: demoCandidates[0].authors,
  year: 2025,
  venue: "NeurIPS 2025",
  status: "ready",
  pageCount: 14,
  analysis: {
    summary: "EAGLE-3 uses a small draft model to propose several tokens, then verifies the proposal in parallel with a shared expert-aware verifier. The paper's central idea is to reduce the serial part of decoding without hiding routing costs.",
    problem: "Autoregressive generation is slow because every next token depends on the previous one. Mixture-of-experts models add another cost: tokens may activate different experts, creating uneven work and communication.",
    motivation: "Existing speculative decoding methods can lose their advantage when verification causes expert imbalance or when draft and target models disagree frequently.",
    keyInsight: "The verifier can accept a variable prefix of draft tokens in one pass if it tracks expert capacity and exposes the acceptance boundary to the scheduler.",
    method: "The system drafts a candidate block, groups its token routes, runs expert computation in parallel, and accepts the longest prefix whose probabilities remain consistent with the target model.",
    contributions: [
      "An expert-aware draft and verification schedule.",
      "A parallel acceptance procedure with an explicit stopping boundary.",
      "An ablation of draft length, verifier width, and expert balance.",
    ],
    results: "The core result is a throughput improvement that grows with draft acceptance, then flattens once expert dispatch and memory bandwidth dominate.",
    limitations: [
      "The method assumes the draft model is cheap enough to keep the verifier fed.",
      "Benefits depend on the serving stack's ability to batch expert routes efficiently.",
      "The evaluation focuses on a small set of model and workload families.",
    ],
    prerequisites: ["Transformer decoding", "mixture-of-experts routing", "softmax probabilities"],
    glossary: [
      { term: "Draft model", definition: "A smaller model that proposes multiple next tokens before the target model checks them." },
      { term: "Acceptance boundary", definition: "The first position where the verifier rejects the proposed token block." },
      { term: "Expert imbalance", definition: "Uneven work across experts that turns parallel execution into a bottleneck." },
    ],
  },
  graph: {
    nodes: [
      { id: "input", label: "Prompt tokens", type: "input", explanation: "The user prompt enters the decoding loop.", evidenceIds: ["E1"] },
      { id: "draft", label: "Draft block", type: "component", explanation: "A lightweight draft model proposes several tokens at once.", evidenceIds: ["E2"] },
      { id: "route", label: "Route tokens", type: "process", explanation: "Proposed tokens are grouped by the experts they activate.", evidenceIds: ["V1"] },
      { id: "verify", label: "Parallel verifier", type: "proposed", explanation: "The target model checks the candidate block in one coordinated pass.", evidenceIds: ["V1", "E3"] },
      { id: "accept", label: "Acceptance boundary", type: "decision", explanation: "The longest consistent prefix becomes the next emitted sequence.", evidenceIds: ["E4"] },
      { id: "result", label: "Emitted tokens", type: "result", explanation: "Accepted tokens advance the autoregressive loop.", evidenceIds: ["E5"] },
    ],
    edges: [
      { id: "e1", source: "input", target: "draft", relation: "flows_to" },
      { id: "e2", source: "draft", target: "route", relation: "produces" },
      { id: "e3", source: "route", target: "verify", relation: "uses" },
      { id: "e4", source: "verify", target: "accept", relation: "produces" },
      { id: "e5", source: "accept", target: "result", relation: "flows_to" },
      { id: "e6", source: "result", target: "draft", relation: "flows_to" },
    ],
  },
  visuals: [
    {
      id: "visual-3",
      paperId: "eagle-3",
      type: "architecture",
      label: "Figure 3",
      pageNumber: 6,
      caption: "Expert-aware speculative decoding pipeline.",
      visualDescription: "A left-to-right pipeline shows draft generation feeding token routing, a parallel verification block, and an acceptance boundary before output.",
      visualInterpretation: "The figure makes the serial-to-parallel handoff explicit. The verifier is not a second independent pipeline; it is the coordination point between draft proposals and expert dispatch.",
      concepts: ["draft generation", "expert routing", "parallel verification"],
    },
    {
      id: "visual-5",
      paperId: "eagle-3",
      type: "plot",
      label: "Figure 5",
      pageNumber: 8,
      caption: "Throughput as draft length increases.",
      visualDescription: "A line plot rises quickly for short draft blocks, then reaches a broad plateau as the x-axis moves past the mid-range.",
      visualInterpretation: "The plateau indicates that increasing proposal length no longer removes the dominant dispatch and memory costs.",
      concepts: ["throughput", "draft length", "memory bandwidth"],
    },
  ],
  demo: true,
};

export const demoJob: { id: string; paperId: string; stages: { label: string; state: "done" | "active" | "next" }[] } = {
  id: "demo-job",
  paperId: "eagle-3",
  stages: [
    { label: "Paper stored", state: "done" },
    { label: "Pages rendered", state: "done" },
    { label: "Gemini analysis", state: "done" },
    { label: "Embeddings indexed", state: "done" },
  ],
};
